{
 "title": "${upsname} [TF]",
 "description": "Example dashboard for HON95's Prometheus NUT Exporter.",
 "tags": [ "terraformed" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{ups=\"${upsname}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage_volts{ups=\"${upsname}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=\"${upsname}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{ups=\"${upsname}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_beeper_status{ups=\"${upsname}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * nut_battery_charge{ups=\"${upsname}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime [1m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime_seconds{ups=\"${upsname}\"}[1m])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load [1m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_load{ups=\"${upsname}\"}[1m])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Voltage [1m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_voltage_volts{ups=\"${upsname}\"}[1m])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage [1m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts{ups=\"${upsname}\"}[1m])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage [1m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_voltage_volts{ups=\"${upsname}\"}[1m])",
     "legendFormat": "{{ups}}"
    }
   ]
  }
 ]
}