{
 "title": "Ping [TF]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ping Loss Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(target) (ping_loss_ratio{ip_version=\"4\", target!=\"96.80.53.25\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Ping Mean RTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(target) (ping_rtt_mean_seconds{ip_version=\"4\", target!=\"96.80.53.25\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Ping Best RTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by(target) (ping_rtt_best_seconds{ip_version=\"4\", target!=\"96.80.53.25\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Ping Worst RTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(target) (ping_rtt_worst_seconds{ip_version=\"4\", target!=\"96.80.53.25\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Ping RTT Std Deviation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(target) (ping_rtt_std_deviation_seconds{ip_version=\"4\", target!=\"96.80.53.25\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Decatur Makers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ping_rtt_std_deviation_seconds{target=\"96.80.53.25\"}",
     "legendFormat": "Standard Deviation"
    },
    {
     "expr": "ping_rtt_mean_seconds{target=\"96.80.53.25\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "ping_rtt_best_seconds{target=\"96.80.53.25\"}",
     "legendFormat": "Best"
    },
    {
     "expr": "ping_rtt_worst_seconds{target=\"96.80.53.25\"}",
     "legendFormat": "Worst"
    },
    {
     "expr": "ping_loss_ratio{target=\"96.80.53.25\"}",
     "legendFormat": "Loss Ratio"
    }
   ]
  }
 ]
}