{
 "title": "Systemd Service Dashboard (1617) [TF]",
 "description": "Show stats from node_exporter systemd collector.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(systemd_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GLOBAL Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GLOBAL Unit State Count (ALL nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "GLOBAL Service Restart Count (ALL nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(systemd_service_restart_total[1m])) by (instance, name) > 0",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Per-Node Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Activating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{instance=~\"$Node:.*\", state=\"activating\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{instance=~\"$Node:.*\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{instance=~\"$Node:.*\", state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{instance=~\"$Node:.*\", state=\"inactive\"})"
    }
   ]
  },
  {
   "title": "Failed Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(systemd_unit_state{instance=~\"$Node:.*\",state=\"failed\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total CPU Time Seconds per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(systemd_process_cpu_seconds_total{instance=~\"$Node:.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemd_process_resident_memory_bytes{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Max FDs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "systemd_process_max_fds{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemd_process_virtual_memory_bytes{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Max",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemd_process_virtual_memory_max_bytes{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Accepted and Refused Socket Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(systemd_socket_accepted_connections_total{instance=~\"$Node:.*\"}[1m])",
     "legendFormat": "{{name}} Accepted"
    },
    {
     "expr": "systemd_socket_refused_connections_total{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}} Refused"
    }
   ]
  },
  {
   "title": "Current Socket Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "systemd_socket_current_connections{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current Tasks Per Unit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "systemd_unit_tasks_current{instance=~\"$Node:.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}