{
 "title": "UniFi-Poller: USW Insights - Prometheus (11312) [TF]",
 "description": "UniFi Poller v2.0.1 Displays detailed information for network switches in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "usw",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": {
     "query": "label_values(unpoller_device_info,source)"
    }
   },
   { "name": "Devices", "query": "udm,usw,uap" },
   {
    "name": "Site",
    "query": {
     "query": "label_values(unpoller_device_info{source=~\"$Controller\"},site_name)"
    }
   },
   {
    "name": "Switch",
    "query": {
     "query": "label_values(unpoller_device_info{site_name=~\"$Site\", type=~\"$Devices\"},name)"
    }
   },
   {
    "name": "Port",
    "query": {
     "query": "label_values(unpoller_device_port_port_speed_bps{site_name=~\"$Site\", name=~\"$Switch\"},port_id)"
    }
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Switch Details",
   "type": "table",
   "description": "If you have access points and gateways they will also show up here because they have switch ports.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_info{site_name=~\"$Site\", name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unpoller_device_bytes_total{site_name=~\"$Site\", name=~\"$Switch\"})"
    }
   ]
  },
  {
   "title": "Device Temperature(s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius", "label": "Celcius" }
   ],
   "targets": [
    {
     "expr": "sum by (name,temp_area,temp_type) (unpoller_device_temperature_celsius{site_name=~\"$Site\",name=~\"$Switch\"})",
     "legendFormat": "{{name}} {{temp_area}} {{temp_type}} C "
    },
    {
     "expr": "sum by (name,temp_area,temp_type) (unpoller_device_temperature_celsius{site_name=~\"$Site\",name=~\"$Switch\"}*9/5+32)",
     "legendFormat": "{{name}} {{temp_area}} {{temp_type}} F"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory Utilization" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_memory_utilization_ratio{type=\"usw\", site_name=~\"$Site\",name=~\"$Switch\",type=~\"usw|udm|udmp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Device Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_load_average_1{site_name=~\"$Site\",name=~\"$Switch\"}",
     "legendFormat": "{{name}} load1"
    },
    {
     "expr": "unpoller_device_load_average_15{site_name=~\"$Site\",name=~\"$Switch\"}",
     "legendFormat": "{{name}} load15"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "unpoller_device_cpu_utilization_ratio{site_name=~\"$Site\",name=~\"$Switch\",type=~\"usw|udm|udmp\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Drops and Errors",
   "type": "timeseries",
   "description": "Shows drops and errors selected switch ports.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "pps", "label": "packets per second" }
   ],
   "targets": [
    {
     "expr": "rate(unpoller_device_port_transmit_dropped_total{site_name=~\"$Site\", name=~\"$Switch\", port_id=~\"$Port\"}[$__interval])",
     "legendFormat": "{{port_id}} {{port_name}} Tx Drops"
    },
    {
     "expr": "rate(unpoller_device_port_receive_dropped_total{site_name=~\"$Site\", name=~\"$Switch\", port_id=~\"$Port\"}[$__interval])",
     "legendFormat": "{{port_id}} {{port_name}} Rx Drops"
    },
    {
     "expr": "rate(unpoller_device_port_transmit_errors_total{site_name=~\"$Site\", name=~\"$Switch\", port_id=~\"$Port\"}[$__interval])",
     "legendFormat": "{{port_id}} {{port_name}} Tx Errors"
    },
    {
     "expr": "rate(unpoller_device_port_receive_errors_total{site_name=~\"$Site\", name=~\"$Switch\", port_id=~\"$Port\"}[$__interval])",
     "legendFormat": "{{port_id}} {{port_name}} Rx Errors"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Shows data transferred for selected switch ports.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes Per Second" }
   ],
   "targets": [
    {
     "expr": "rate(unpoller_device_port_transmit_bytes_total{site_name=~\"$Site\", name=~\"$Switch\", port_id=~\"$Port\"}[$__interval])",
     "legendFormat": "{{port_id}} {{port_name}} Tx"
    },
    {
     "expr": "rate(unpoller_device_port_receive_bytes_total{site_name=~\"$Site\", name=~\"$Switch\", port_id=~\"$Port\"}[$__interval])",
     "legendFormat": "{{port_id}} {{port_name}} Rx"
    }
   ]
  },
  {
   "title": "All Port Information",
   "type": "table",
   "description": "This panel displays lifetime totals and current data as of now.",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_receive_bytes_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_transmit_bytes_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_receive_dropped_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_transmit_dropped_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_receive_broadcast_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_transmit_broadcast_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_receive_errors_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_transmit_errors_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_receive_packets_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_transmit_packets_total{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_poe_amperes{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_poe_volts{site_name=~\"$Site\",name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (name,port_num,port_name,site_name,source) (unpoller_device_port_poe_watts{site_name=~\"$Site\",name=~\"$Switch\"})"
    }
   ]
  },
  {
   "title": "Switch $Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "repeat": "Port",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Switch $Port Information",
     "type": "table",
     "description": "These are total \"lifetime\" counters.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "unpoller_device_port_port_speed_bps{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Speed"
      },
      {
       "expr": "unpoller_device_port_poe_amperes{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Amps"
      },
      {
       "expr": "unpoller_device_port_poe_volts{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Volts"
      },
      {
       "expr": "unpoller_device_port_poe_watts{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Watts"
      },
      {
       "expr": "unpoller_device_port_transmit_broadcast_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Tx Broadcast"
      },
      {
       "expr": "unpoller_device_port_transmit_multicast_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Rx Multicast"
      },
      {
       "expr": "unpoller_device_port_receive_dropped_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Rx Drops"
      },
      {
       "expr": "unpoller_device_port_transmit_dropped_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Tx Drops"
      },
      {
       "expr": "unpoller_device_port_transmit_errors_total+unpoller_device_port_receive_errors_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Rx+Tx Errors"
      },
      {
       "expr": "unpoller_device_port_receive_packets_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Rx Packets"
      },
      {
       "expr": "unpoller_device_port_transmit_packets_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Tx Packets"
      },
      {
       "expr": "unpoller_device_port_receive_bytes_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Bytes Rx"
      },
      {
       "expr": "unpoller_device_port_transmit_bytes_total{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Bytes Tx"
      },
      {
       "expr": "unpoller_device_port_satisfaction_percent{port_id=\"$Port\", site_name=~\"$Site\"}",
       "legendFormat": "Satisfaction"
      }
     ]
    },
    {
     "title": "Data Transfer: Switch $Port",
     "type": "timeseries",
     "description": "Shows data transfer rate per second for Switch $Port. TX on positive axis and RX on negative axis.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes / Second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_port_receive_bytes_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": " {{port_id}} ({{port_name}}) Rx"
      },
      {
       "expr": "rate(unpoller_device_port_transmit_bytes_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": " {{port_id}} ({{port_name}}) Tx"
      }
     ]
    },
    {
     "title": "Multicast & Broadcast: Switch $Port",
     "type": "timeseries",
     "description": "Shows broadcast and multicast packets per second for Switch $Port. TX on positive axis and RX on negative axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "pps", "label": "PPS" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_port_receive_broadcast_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Broadcast Rx"
      },
      {
       "expr": "rate(unpoller_device_port_transmit_broadcast_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Broadcast Tx"
      },
      {
       "expr": "rate(unpoller_device_port_receive_multicast_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Multicast Rx"
      },
      {
       "expr": "rate(unpoller_device_port_transmit_multicast_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Multicast Tx"
      }
     ]
    },
    {
     "title": "Errors and Drops: Switch $Port",
     "type": "timeseries",
     "description": "Shows errors and dropped packets for Switch $Port. RX on negative axis.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "pps", "label": "packets per second" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_port_receive_dropped_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Drops Rx"
      },
      {
       "expr": "rate(unpoller_device_port_transmit_dropped_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Drops Tx"
      },
      {
       "expr": "rate(unpoller_device_port_transmit_errors_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Errors Tx"
      },
      {
       "expr": "rate(unpoller_device_port_receive_errors_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Errors Rx"
      }
     ]
    },
    {
     "title": "Packets Per Second: Switch $Port",
     "type": "timeseries",
     "description": "Shows packet counters for Switch $Port. TX on positive axis and RX on negative axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "pps", "label": "PPS" }
     ],
     "targets": [
      {
       "expr": "rate(unpoller_device_port_receive_packets_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Rx"
      },
      {
       "expr": "rate(unpoller_device_port_transmit_packets_total{site_name=~\"$Site\", port_id=~\"$Port\"}[$__interval])",
       "legendFormat": "{{port_id}} ({{port_name}}) Tx"
      }
     ]
    },
    {
     "title": "POE Power: Switch $Port",
     "type": "timeseries",
     "description": "Display POE Power for Switch $Port.",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "watt", "label": "Watts" }
     ],
     "targets": [
      {
       "expr": "unpoller_device_port_poe_watts{site_name=~\"$Site\", port_id=~\"$Port\"}",
       "legendFormat": "{{port_id}}  Watts"
      }
     ]
    },
    {
     "title": "POE Voltage: Switch $Port",
     "type": "timeseries",
     "description": "Display POE Voltage for Switch $Port.",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "volt", "label": "Volts" }
     ],
     "targets": [
      {
       "expr": "unpoller_device_port_poe_volts{site_name=~\"$Site\", port_id=~\"$Port\"}",
       "legendFormat": "{{port_id}} Volts"
      }
     ]
    },
    {
     "title": "POE Current: Switch $Port",
     "type": "timeseries",
     "description": "Display POE Current for Switch $Port.",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 80 },
     "yaxes": [
      { "format": "mamp", "label": "Amps" }
     ],
     "targets": [
      {
       "expr": "unpoller_device_port_poe_amperes{site_name=~\"$Site\", port_id=~\"$Port\"}",
       "legendFormat": "{{port_id}} Amps"
      }
     ]
    }
   ]
  },
  {
   "title": "Purposely Empty Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "targets": [
    {}
   ]
  }
 ]
}